const mongoose = require('mongoose');

const propertyFeatureSchema = new mongoose.Schema({
  id: Number,
  property_id: Number,
  surface_effective_m2: Number,
  dist_ecole: Number,
  dist_hopital: Number,
  dist_pharmacie: Number,
  dist_banque: Number,
  dist_restaurant: Number,
  dist_hotel: Number,
  dist_commerce: Number,
  dist_station_service: Number,
  dist_route_principale: Number,
  nb_pois_500m: Number,
  nb_pois_1km: Number,
  nb_pois_2km: Number,
  nb_ecoles_1km: Number,
  nb_restaurants_1km: Number,
  nb_hotels_2km: Number,
  nb_commerces_1km: Number,
  densite_poi_1km: Number,
  diversite_poi_1km: Number,
  zoning_code: String,
  zone_category: String,
  in_zone_touristique: Boolean,
  in_zone_industrielle: Boolean,
  in_planning_boundary: Boolean,
  en_zone_urbaine: Boolean,
  couvert_par_pa: Boolean,
  statut_foncier: String,
  litige_en_cours: Boolean,
  hypotheque_active: Boolean,
  saisie_active: Boolean,
  servitude_active: Boolean,
  taux_chomage_region: Number,
  revenu_moyen_region: Number,
  taux_urbanisation: Number,
  prix_moyen_quartier: Number,
  prix_m2_moyen_quartier: Number,
  nb_annonces_quartier: Number,
  nb_equipements: Number,
  has_piscine: Boolean,
  has_parking: Boolean,
  has_securite: Boolean,
  has_climatisation: Boolean,
  has_ascenseur: Boolean,
  nb_projets_urbains_commune: Number,
  nb_lotissements_commune: Number,
  nb_hotels_region: Number,
  computed_at: Date,
  commune_nom: String,
  foncier_source: String,
  foncier_distance_m: Number,
  dist_transport: Number,
  nb_transport_500m: Number,
  nb_transport_1km: Number,
}, { collection: 'property_features', strict: false });

propertyFeatureSchema.index({ property_id: 1 });

module.exports = mongoose.model('PropertyFeature', propertyFeatureSchema);
